# Generated by Django 4.2.1 on 2023-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.CharField(choices=[('3 года', '3 года'), ('4 года', '4 года'), ('5 лет', '5 лет'), ('6 лет', '6 лет'), ('7лет', '7 лет')], max_length=20),
        ),
    ]
