# Generated by Django 4.2.1 on 2023-06-09 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0002_alter_game_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_name', models.CharField(choices=[('3 года', '3 года'), ('4 года', '4 года'), ('5 лет', '5 лет'), ('6 лет', '6 лет'), ('7лет', '7 лет')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traning.ages', verbose_name='Возраст'),
        ),
    ]
